import NegDROFormalization.AveragedPrimalIterate
import NegDROFormalization.AdditiveInterventionPopulationBridge
import NegDROFormalization.AdditiveInterventionPopulationInterfaces
import NegDROFormalization.AdditiveInterventionSamplingBridge
import NegDROFormalization.AdditiveInterventionSamplingConvergence
import NegDROFormalization.AdditiveInterventionSamplingProjectedConvergence
import NegDROFormalization.Basic
import NegDROFormalization.Comparator
import NegDROFormalization.ConcreteComparator
import NegDROFormalization.ConcreteOracleMomentBounds
import NegDROFormalization.ConcreteStochasticOracles
import NegDROFormalization.ConditionalExpectationScalar
import NegDROFormalization.DualRegretTelescoping
import NegDROFormalization.DualObjectiveLinearization
import NegDROFormalization.EGTrajectoryRegret
import NegDROFormalization.EntropyGeometry
import NegDROFormalization.EuclideanProjectionBridge
import NegDROFormalization.ExponentiatedGradient
import NegDROFormalization.ExpandedPrimalCoefficient
import NegDROFormalization.ExpectedConcretePrimalDirection
import NegDROFormalization.ExpectedDualRegret
import NegDROFormalization.ExpectedEGTrajectoryRegret
import NegDROFormalization.ExpectedPrimalRecursion
import NegDROFormalization.FinitePinsker
import NegDROFormalization.FreshFiniteEnvironmentMoments
import NegDROFormalization.FreshSamplingLaw
import NegDROFormalization.FreshSamplingConditionalOracles
import NegDROFormalization.MirrorRemainderBound
import NegDROFormalization.OracleIntegrabilityBridge
import NegDROFormalization.FixedWitness
import NegDROFormalization.PopulationExpansion
import NegDROFormalization.PopulationRiskMomentBridge
import NegDROFormalization.PrimalProjectionRecursion
import NegDROFormalization.PrimalTrajectory
import NegDROFormalization.PredictableVectorPairing
import NegDROFormalization.QuadraticStructure
import NegDROFormalization.RegretToConvergence
import NegDROFormalization.SecondMomentMatrixBridge
import NegDROFormalization.Simplex
import NegDROFormalization.SpectralCurvatureBridge
import NegDROFormalization.SpectralWitnessInterface
import NegDROFormalization.StochasticDualRegret
import NegDROFormalization.StochasticNegDROConvergence
import NegDROFormalization.StochasticNegDROConvergencePredictable
import NegDROFormalization.StochasticNegDROExplicitConstants
import NegDROFormalization.StochasticNegDRORates
import NegDROFormalization.StochasticPrimalTrajectory
import NegDROFormalization.TrajectoryPredictability
import NegDROFormalization.UpdateMeasurability
import NegDROFormalization.YoungVector

/-!
# NegDROFormalization

The project overview and verified scope are documented in `README.md`. Detailed cross-references
are in `docs/FORMALIZATION_COVERAGE.md`, `docs/THEOREM_MAP.md`,
`docs/ASSUMPTION_LEDGER.md`, and `docs/COMPLETION_ROADMAP.md`.
-/
